<?php 
/* 
*      Robo Gallery     
*      Version: 3.2.14 - 40722
*      By Robosoft
*
*      Contact: https://robogallery.co/ 
*      Created: 2021
*      Licensed under the GPLv2 license - http://opensource.org/licenses/gpl-2.0.php

 */ 
?>
<div class="rbsDashboardGallery-div">
    <h2><?php _e( 'Need some Help ?', 'robo-gallery' );?></h2>
    <p class="rbsDashboardGallery-p"><?php
        echo sprintf(  __( 'If you have some questions or any kind of problems with gallery installation or configuration feel free to <a href="%s">post ticket here</a>. ', 'robo-gallery' ), 'https://wordpress.org/support/plugin/robo-gallery' ); 
        ?> <br/>  <?php 
        echo sprintf(  __( 'If you have some new features request or some functionality update for our gallery plugin please <a href="%s">post some message</a> with description.', 'robo-gallery' ), 'https://wordpress.org/support/plugin/robo-gallery' ); 
        ?>
    </p>
    <a class="button button-primary button-hero " href="https://wordpress.org/support/plugin/robo-gallery" target="blank"><?php _e( 'Post Support Ticket', 'robo-gallery' );?></a>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/3vBl9Ke6bsg" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'Robo Gallery Key Installation', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'this video show how to install key for activation premium features of the robo gallery', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/-CuGOo7XRmQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'Robo Gallery - Drag and Drop Categories Management', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'in robo gallery you can use drag and drop editor for configuration of the categories three. Here you can see how to create sub categories for main galleries', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/fI3uYOlUbo4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'Upload Robo Gallery Images', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'video show process of the upload and management of the gallery images resources. Check how to use additional options of the images. Where to specify links and video links for the gallery images', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/lxDR6E8erBA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'How to use Robo Gallery shortcode', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'every created gallery have different shortcode with ID. You can use gallery inside generated by default post, in gallery widget or use short code in any post or page', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/RrWn8tMuKsw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'Robo Gallery Post Generator', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'every gallery have section where you can manage posts which generated for every gallery item', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/mZ_yOXkxRsk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'Polaroid style configuration in Robo Gallery', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'please watch this video to see how to setup Polaroid style gallery in few simple steps. For the content panel below thumbnails you can use description, title or caption of the images', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/DdCpRuLFxzk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'Robo Gallery grid layout configuration', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'in robo gallery you can fully customize layout of the thumbnails. Create classic grid, grid with different size thumbnails, masonry layout. You have no limits for customization', 'robo-gallery' ); ?></p>

    </div>
</div>

<div class="changelog">
    <div class="feature-section">

        <iframe class="rbsDashboardGallery-video" width="560" height="315" src="https://www.youtube.com/embed/m9XIeqMnhYI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

        <h2><?php _e( 'First gallery configuration', 'robo-gallery' );?></h2>
        <p class="rbsDashboardGallery-p"><?php _e( 'robo gallery do not require any special skills for configuration of your first gallery. Configuration settings is really simple. Just click Add Gallery link on the left side, upload images to the Image Manager and save first gallery with custom title. In the list of the galleries you can find new created gallery with direct link to the front end post generated for this new gallery item', 'robo-gallery' ); ?></p>

    </div>
</div>
